import{a as v,S as P,i as q}from"./assets/vendor-06b1bbdf.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();async function h(o,t=1){const c="https://pixabay.com",n="/api/",e="?key=43218628-434600724cd02d3e35d2dc910",r=`&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${t}`,s=c+n+e+r;try{return(await v.get(s)).data}catch(l){throw new Error(l.response.status)}console.log(s)}const u=document.querySelector(".gallery");u||console.error("Gallery element not found on the page");function p(o){const t=o.hits.map(({webformatURL:n,largeImageURL:e,tags:r,likes:s,views:l,comments:w,downloads:S})=>`<li class="gallery-item">
  <a class="gallery-link" href="${e}">
    <img class="gallery-img" src="${n}" alt="${r}" />
    <div class="image-description">
      <p class="info-item"><b>Likes: </b>${s}</p>
      <p class="info-item"><b>Views: </b>${l}</p>
      <p class="info-item"><b>Comments: </b>${w}</p>
      <p class="info-item"><b>Downloads: </b>${S}</p>
    </div>
  </a>
</li>`).join("");u.insertAdjacentHTML("beforeend",t),new P(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",captionPosition:"bottom"}).refresh()}const $=document.querySelector(".img-search-form"),g=document.querySelector(".loader"),f=document.querySelector(".load-more-btn");let d,a,y;$.addEventListener("submit",M);f.addEventListener("click",O);async function M(o){if(o.preventDefault(),b(),u.innerHTML="",d=o.target.elements.query.value.trim(),a=1,d===""){i("Sorry, there are no search terms entered. Please try again!");return}L();try{const t=await h(d,a);if(y=Math.ceil(t.totalHits/15),t.totalHits===0){m(),i("Sorry, there are no images matching your search query. Please try again!");return}p(t)}catch(t){i(t)}m(),E(),o.target.reset()}async function O(){a+=1,L();try{const t=await h(d,a);p(t)}catch(t){i(t)}m(),E();const o=u.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:o*2})}function x(){f.classList.remove("hidden")}function b(){f.classList.add("hidden")}function L(){g.classList.remove("hidden")}function m(){g.classList.add("hidden")}function i(o){q.error({message:o,messageColor:"white",backgroundColor:"red",position:"topRight"})}function E(){a>=y?(b(),i("We're sorry, but you've reached the end of search results.")):x()}
//# sourceMappingURL=commonHelpers.js.map
